language: node_js
node_js:
  - "node"

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
  - source ~/.bash_profile
  - tiup playground v4.0.0 --monitor false --tiflash 0 &
  - sleep 30

install:
  - yarn

script:
  - yarn build && yarn test

cache: yarn
