language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - git clone https://github.com/pingcap/tidb-docker-compose.git --depth 1
  - cd tidb-docker-compose && docker-compose up -d

install:
  - yarn

script:
  - yarn build && yarn test

cache: yarn
